# Generated by Django 5.0.2 on 2024-02-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_delete_receipe_view_receipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='update_receipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_description', models.CharField(max_length=100)),
            ],
        ),
    ]
