# Generated by Django 5.0.2 on 2024-02-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_update_receipes_new_receipe_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='update_receipes',
            new_name='receipes_update',
        ),
    ]
