# Generated by Django 5.0.2 on 2024-02-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_rename_update_receipes_receipes_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipes_update',
            old_name='receipe_description',
            new_name='new_receipe_description',
        ),
    ]
